// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQl2r7ByPz0_8gfSwKV2CMiaGYO082loM',
    appId: '1:598305626594:web:8733a4b0ce4819537041bb',
    messagingSenderId: '598305626594',
    projectId: 'test-notification-b7913',
    authDomain: 'test-notification-b7913.firebaseapp.com',
    storageBucket: 'test-notification-b7913.appspot.com',
    measurementId: 'G-W4LVYH47YX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTUbwyKVALu4qbLPUm1qgxg5pvLQooA2U',
    appId: '1:598305626594:android:1006474600031ee07041bb',
    messagingSenderId: '598305626594',
    projectId: 'test-notification-b7913',
    storageBucket: 'test-notification-b7913.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqmX_q_W3Lp-c14DrUZkR-rXSnXXnogzk',
    appId: '1:598305626594:ios:16d5a44361d8bd477041bb',
    messagingSenderId: '598305626594',
    projectId: 'test-notification-b7913',
    storageBucket: 'test-notification-b7913.appspot.com',
    iosClientId: '598305626594-o57bu2na3kvr0hamb7isj9sil6gfsv57.apps.googleusercontent.com',
    iosBundleId: 'com.example.handleNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqmX_q_W3Lp-c14DrUZkR-rXSnXXnogzk',
    appId: '1:598305626594:ios:841e2f65cbaac0dc7041bb',
    messagingSenderId: '598305626594',
    projectId: 'test-notification-b7913',
    storageBucket: 'test-notification-b7913.appspot.com',
    iosClientId: '598305626594-2jtgi2eldj9m1djoeidu4kfq3c2qtgi6.apps.googleusercontent.com',
    iosBundleId: 'com.example.handleNotification.RunnerTests',
  );
}
